version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'tuesday'
          time: '12:00'
          timezone: 'America/Los_Angeles'
      open-pull-requests-limit: 5
      reviewers:
          - 'adixon-adobe'
          - 'westbrook'
