# Temporarily disable dependabot PRs
version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'tuesday'
          time: '12:00'
          timezone: 'America/Los_Angeles'
      # Set open-pull-requests-limit to 0 to disable PRs
      open-pull-requests-limit: 0
      reviewers:
          - 'adobe/swc-maintainers'
      groups:
          # Specify a name for the group, which will be used in pull request titles
          # and branch names
          storybook-ecosystem:
              # Define patterns to include dependencies in the group (based on
              # dependency name)
              patterns:
                  - 'storybook'
                  - '@storybook/*'
                  - '@types/storybook*'
          commitlint-ecosystem:
              patterns:
                  - '@commitlint/*'
                  - 'commitlint'
          eleventy-ecosystem:
              patterns:
                  - '@11ty/*'
                  - 'eleventy'
                  - 'eleventy-plugin-*'
          web-and-open-wc-ecosystem:
              patterns:
                  - '@open-wc/*'
                  - '@web/*'

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'monthly'
      # Set open-pull-requests-limit to 0 to disable PRs
      open-pull-requests-limit: 0
