name: Visual regression testing with Chromatic

on:
    pull_request:
        paths:
            - '2nd-gen/**'
    workflow_dispatch:
    workflow_call:
        inputs:
            skip:
                description: 'Skip running VRT'
                required: false
                type: boolean
                default: false
        outputs:
            storybook-url:
                description: 'URL of the published Storybook'
                value: ${{ jobs.chromatic.outputs.storybook-url }}

permissions:
    contents: read
    pull-requests: write

jobs:
    chromatic:
        name: Chromatic
        runs-on: ubuntu-latest
        timeout-minutes: 20
        outputs:
            storybook-url: ${{ steps.chromatic.outputs.storybookUrl != 'undefined' && steps.chromatic.outputs.storybookUrl || '' }}

        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Job and Install Dependencies
              uses: ./.github/actions/setup-job

            - name: Generate Custom Elements Manifest
              working-directory: 2nd-gen/packages/swc
              run: yarn analyze

            - name: Publish to Chromatic
              id: chromatic
              uses: chromaui/action@latest
              with:
                  projectToken: ${{ secrets.CHROMATIC_TOKEN }}
                  workingDir: 2nd-gen/packages/swc
                  skip: ${{ inputs.skip }}
