name: Preview Release

on:
    # push:
    #     branches:
    #         - main
    pull_request:
        types: [opened, synchronize]

jobs:
    release:
        runs-on: ubuntu-latest
        env:
            YARN_ENABLE_IMMUTABLE_INSTALLS: false
        # Run the job if manually triggered or if the commit message includes a commit type of fix or feat or breaking change
        # if: contains(github.event.head_commit.message, 'fix:') || contains(github.event.head_commit.message, 'fix(') || contains(github.event.head_commit.message, 'feat:') || contains(github.event.head_commit.message, 'feat(') || contains(github.event.head_commit.message, '!:')
        steps:
            - name: Checkout PR branch
              uses: actions/checkout@v4

            - name: Setup Job and Install Dependencies
              uses: ./.github/actions/setup-job

            - name: Set Git identity
              run: |
                  git config --global user.email "support+actions@github.com"
                  git config --global user.name "github-actions-bot"

            - name: Update package versions for preview snapshot release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  yarn changeset version --snapshot preview-${GITHUB_SHA::8}
                  yarn genversion --source ./1st-gen/tools/base/package.json --semi --es6 --force ./2nd-gen/packages/core/shared/base/version.ts
                  yarn install --refresh-lockfile

            - name: Configure NPM for changeset publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

            - name: Publish preview snapshot release
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  yarn build
                  git add .
                  git commit -am "chore: publish preview snapshot version"
                  yarn changeset publish --no-git-tag --tag preview
                  git reset --hard HEAD^
