name: Publish Documentation Site

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    site-build:
        name: Build & publish site
        runs-on: ubuntu-latest
        # Run the job if manually triggered or if the commit message includes '#publish' & the check suite has passed or if the commit message includes 'docs' and the check suite has passed
        if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '#publish') || contains(github.event.head_commit.message, 'docs:') || contains(github.event.head_commit.message, 'docs(')
        steps:
            - name: Checkout PR branch
              uses: actions/checkout@v4

            - name: Setup Job and Install Dependencies
              uses: ./.github/actions/setup-job

            - name: Generate Custom Elements Manifest
              run: yarn workspace @spectrum-web-components/1st-gen docs:analyze

            - name: Move CEM to Storybook directory
              run: cp 1st-gen/projects/documentation/custom-elements.json 1st-gen/storybook/

            - name: Build documentation
              run: yarn workspace @spectrum-web-components/1st-gen docs:production

            - name: Build Storybook
              run: yarn workspace @spectrum-web-components/1st-gen storybook:build

            - name: Add redirects to documentation
              run: echo '/*    /index.html   200' > 1st-gen/projects/documentation/dist/_redirects

            - name: Deploy to GitHub Pages
              run: |
                  git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                  yarn gh-pages -d 1st-gen/projects/documentation/dist -m "[skip ci] update demonstration site" -t -u "github-actions-bot <support+actions@github.com>" --nojekyll
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
